## 📌 What is Data Science?

**Data Science** is the practice of **extracting insights and knowledge** from data using techniques such as:
- Statistical Analysis
- Machine Learning

It involves:
- 📥 Collecting Data  
- 🧹 Cleaning Data  
- 📊 Analyzing Data  

These help solve complex problems and support **data-driven decision-making**.

---

## 🎯 Why Learn Data Science?

### ✅ Key Reasons:
- **Uncover Valuable Insights**  
- **Make Informed Decisions**  
- **Solve Real-World Problems**

It helps identify:
- 📈 Patterns  
- 📉 Trends  
- 🔗 Correlations  

These lead to:
- Improved business strategies  
- Optimized processes  
- Predictive models  

---

## 🌍 Real-World Applications:
- 💼 Business  
- 🏥 Healthcare  
- 💳 Finance  
- 🚚 Logistics  
- 📢 Marketing  

---

## 🚀 Benefits:
- Gain a **competitive edge**
- Drive **innovation**
- Enable smarter **data-driven decisions**

---

## 👩‍💼 Career Impact:
As a data scientist, you:
- Study data trends
- Advise organizations
- Get paid to help companies make strategic decisions based on data

---

## 🐍 What's Next?

In the next section, you'll learn how **Python** helps you:
- Load and process data
- Visualize insights
- Build predictive models

📚 _Stay tuned for hands-on learning with libraries like NumPy, Pandas, and Matplotlib._


# NumPy Methods Categorized with Descriptions

---

## 1. Array Creation

| Method                     | Description                                       |
|----------------------------|---------------------------------------------------|
| `np.array()`               | Creates a NumPy array from a Python list or tuple |
| `np.zeros()`               | Creates an array filled with zeros                |
| `np.ones()`                | Creates an array filled with ones                 |
| `np.full()`                | Creates an array filled with a specified value    |
| `np.eye()`                 | Creates an identity matrix                        |
| `np.arange()`              | Returns evenly spaced values within a range       |
| `np.linspace()`            | Returns evenly spaced numbers over an interval    |
| `np.random.rand()`         | Random values in a given shape (uniform [0,1))    |
| `np.random.randn()`        | Random values from standard normal distribution   |
| `np.random.randint()`      | Random integers within a range                    |

---

## 2. Array Manipulation

| Method                     | Description                                     |
|----------------------------|-------------------------------------------------|
| `np.reshape()`             | Gives a new shape to an array                   |
| `np.ravel()`               | Flattens array into 1D (view if possible)       |
| `np.flatten()`             | Flattens array into 1D (always copy)            |
| `np.transpose()`           | Transposes array axes                           |
| `np.vstack()`              | Stacks arrays vertically                        |
| `np.hstack()`              | Stacks arrays horizontally                      |
| `np.concatenate()`         | Joins a sequence of arrays                      |
| `np.split()`               | Splits array into multiple sub-arrays           |

---

## 3. Mathematical Operations

| Method                     | Description                                     |
|----------------------------|-------------------------------------------------|
| `np.add()`                 | Element-wise addition                           |
| `np.subtract()`            | Element-wise subtraction                        |
| `np.multiply()`            | Element-wise multiplication                     |
| `np.divide()`              | Element-wise division                           |
| `np.power()`               | Element-wise exponentiation                     |
| `np.exp()`                 | Exponential of array elements                   |
| `np.sqrt()`                | Square root of each element                     |
| `np.sin()`, `np.cos()`     | Trigonometric functions                         |
| `np.dot()`                 | Dot product of two arrays                       |
| `np.mean()`                | Average of elements                             |
| `np.median()`              | Median of elements                              |
| `np.std()`                 | Standard deviation                              |
| `np.sum()`                 | Sum of array elements                           |
| `np.max()` / `np.min()`    | Maximum/Minimum value                           |
| `np.argmax()` / `np.argmin()`| Index of max/min value                        |

---

## 4. Logical and Comparison

| Method                     | Description                                     |
|----------------------------|-------------------------------------------------|
| `np.equal()`               | Compare for equality                           |
| `np.greater()`, `np.less()`| Compare for greater/less than                  |
| `np.where()`               | Returns elements based on condition            |
| `np.any()` / `np.all()`    | Checks if any/all elements are True            |

---

## 5. Utility Methods

| Method                     | Description                                     |
|----------------------------|-------------------------------------------------|
| `np.unique()`              | Returns unique elements                        |
| `np.sort()`                | Returns sorted array                           |
| `np.argsort()`             | Indices that would sort the array              |
| `np.clip()`                | Clamps values within a range                   |
| `np.isfinite()`            | Checks for finite values                       |
| `np.isnan()`               | Checks for NaN values                          |


In [2]:
import numpy as np

print("🔹 1. ARRAY CREATION METHODS")

a = np.array([[1, 2], [3, 4]])
print("np.array():\n", a)

zeros = np.zeros((2, 2))
print("np.zeros():\n", zeros)

ones = np.ones((2, 3))
print("np.ones():\n", ones)

full = np.full((2, 2), 7)
print("np.full():\n", full)

identity = np.eye(3)
print("np.eye():\n", identity)

range_arr = np.arange(0, 10, 2)
print("np.arange():", range_arr)

linspace_arr = np.linspace(0, 1, 5)
print("np.linspace():", linspace_arr)

rand_arr = np.random.rand(2, 2)
print("np.random.rand():\n", rand_arr)

randn_arr = np.random.randn(2, 2)
print("np.random.randn():\n", randn_arr)

randint_arr = np.random.randint(1, 10, (2, 2))
print("np.random.randint():\n", randint_arr)

print("\n🔹 2. ARRAY MANIPULATION")

reshaped = a.reshape((4, 1))
print("np.reshape():\n", reshaped)

flattened = a.flatten()
print("np.flatten():", flattened)

raveled = a.ravel()
print("np.ravel():", raveled)

transposed = a.T
print("np.transpose() / .T:\n", transposed)

vstacked = np.vstack((a, a))
print("np.vstack():\n", vstacked)

hstacked = np.hstack((a, a))
print("np.hstack():\n", hstacked)

concatenated = np.concatenate((a, a), axis=0)
print("np.concatenate():\n", concatenated)

split_arr = np.array_split(range_arr, 2)
print("np.array_split():", split_arr)

print("\n🔹 3. MATHEMATICAL OPERATIONS")

added = np.add(a, 1)
print("np.add():\n", added)

subtracted = np.subtract(a, 1)
print("np.subtract():\n", subtracted)

multiplied = np.multiply(a, 2)
print("np.multiply():\n", multiplied)

divided = np.divide(a, 2)
print("np.divide():\n", divided)

powered = np.power(a, 2)
print("np.power():\n", powered)

squared_root = np.sqrt(a)
print("np.sqrt():\n", squared_root)

sine = np.sin(a)
print("np.sin():\n", sine)

cosine = np.cos(a)
print("np.cos():\n", cosine)

dot_product = np.dot(a, a)
print("np.dot():\n", dot_product)

mean_val = np.mean(a)
print("np.mean():", mean_val)

median_val = np.median(a)
print("np.median():", median_val)

std_dev = np.std(a)
print("np.std():", std_dev)

total_sum = np.sum(a)
print("np.sum():", total_sum)

max_val = np.max(a)
print("np.max():", max_val)

min_val = np.min(a)
print("np.min():", min_val)

argmax_idx = np.argmax(a)
print("np.argmax():", argmax_idx)

argmin_idx = np.argmin(a)
print("np.argmin():", argmin_idx)

print("\n🔹 4. LOGICAL AND COMPARISON")

eq = np.equal(a, 2)
print("np.equal():\n", eq)

greater = np.greater(a, 2)
print("np.greater():\n", greater)

less = np.less(a, 2)
print("np.less():\n", less)

where_ex = np.where(a > 2, a, 0)
print("np.where():\n", where_ex)

any_true = np.any(a > 3)
print("np.any():", any_true)

all_true = np.all(a < 5)
print("np.all():", all_true)

print("\n🔹 5. UTILITY METHODS")

unique_vals = np.unique([1, 2, 2, 3, 3])
print("np.unique():", unique_vals)

sorted_arr = np.sort([3, 1, 2])
print("np.sort():", sorted_arr)

argsorted = np.argsort([3, 1, 2])
print("np.argsort():", argsorted)

clipped = np.clip([1, 3, 5], 2, 4)
print("np.clip():", clipped)

finite_check = np.isfinite([1, np.inf])
print("np.isfinite():", finite_check)

nan_check = np.isnan([np.nan, 1])
print("np.isnan():", nan_check)


🔹 1. ARRAY CREATION METHODS
np.array():
 [[1 2]
 [3 4]]
np.zeros():
 [[0. 0.]
 [0. 0.]]
np.ones():
 [[1. 1. 1.]
 [1. 1. 1.]]
np.full():
 [[7 7]
 [7 7]]
np.eye():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.arange(): [0 2 4 6 8]
np.linspace(): [0.   0.25 0.5  0.75 1.  ]
np.random.rand():
 [[0.72400401 0.07475919]
 [0.90514054 0.38737154]]
np.random.randn():
 [[ 0.68159465 -0.90934455]
 [-1.12075418  0.61848574]]
np.random.randint():
 [[1 7]
 [2 5]]

🔹 2. ARRAY MANIPULATION
np.reshape():
 [[1]
 [2]
 [3]
 [4]]
np.flatten(): [1 2 3 4]
np.ravel(): [1 2 3 4]
np.transpose() / .T:
 [[1 3]
 [2 4]]
np.vstack():
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]
np.hstack():
 [[1 2 1 2]
 [3 4 3 4]]
np.concatenate():
 [[1 2]
 [3 4]
 [1 2]
 [3 4]]
np.array_split(): [array([0, 2, 4]), array([6, 8])]

🔹 3. MATHEMATICAL OPERATIONS
np.add():
 [[2 3]
 [4 5]]
np.subtract():
 [[0 1]
 [2 3]]
np.multiply():
 [[2 4]
 [6 8]]
np.divide():
 [[0.5 1. ]
 [1.5 2. ]]
np.power():
 [[ 1  4]
 [ 9 16]]
np.sqrt():
 [[1.         1.41421356]
 [1

# 🐼 Pandas Methods Overview

Pandas is a powerful data analysis library for handling structured data. Below are the most commonly used Pandas methods grouped by functionality:

---

## 📘 1. Data Creation & Inspection

| Method                    | Description                               |
|---------------------------|-------------------------------------------|
| `pd.DataFrame()`          | Create a DataFrame                        |
| `pd.Series()`             | Create a Series                           |
| `df.head(n)`              | First `n` rows                            |
| `df.tail(n)`              | Last `n` rows                             |
| `df.shape`                | Returns tuple (rows, columns)             |
| `df.info()`               | Summary of DataFrame                      |
| `df.describe()`           | Statistical summary                       |
| `df.columns`              | List of column names                      |
| `df.index`                | Index labels                              |
| `df.dtypes`               | Data types of columns                     |

---

## 🔍 2. Data Selection & Filtering

| Method                         | Description                                 |
|--------------------------------|---------------------------------------------|
| `df['col']` or `df.col`        | Select a column                             |
| `df[['col1', 'col2']]`         | Select multiple columns                     |
| `df.loc[row_label, col_label]` | Label-based selection                       |
| `df.iloc[row_idx, col_idx]`    | Index-based selection                       |
| `df[df['col'] > val]`          | Filter rows based on condition              |
| `df.query('col > val')`        | SQL-like row filter                         |

---

## 🧹 3. Data Cleaning

| Method                  | Description                              |
|-------------------------|------------------------------------------|
| `df.isnull()`           | Detect missing values                    |
| `df.notnull()`          | Detect non-missing values                |
| `df.dropna()`           | Drop rows with NaN                       |
| `df.fillna(val)`        | Replace NaNs with a value                |
| `df.replace(a, b)`      | Replace values                           |
| `df.duplicated()`       | Identify duplicates                      |
| `df.drop_duplicates()`  | Drop duplicate rows                      |
| `df.astype(type)`       | Convert data types                       |

---

## 🔄 4. Data Transformation

| Method                      | Description                          |
|-----------------------------|--------------------------------------|
| `df.sort_values(by='col')` | Sort by column                       |
| `df.sort_index()`           | Sort by index                        |
| `df.rename(columns=...)`    | Rename columns                       |
| `df.apply(func)`            | Apply function to rows/columns       |
| `df.map(func)`              | Map function (for Series)            |
| `df.astype(type)`           | Convert types                        |
| `df.round(decimals)`        | Round numbers                        |
| `df.clip(lower, upper)`     | Clip values to a range               |

---

## 📊 5. Aggregation & Grouping

| Method                     | Description                         |
|----------------------------|-------------------------------------|
| `df.sum()`                 | Column-wise sum                     |
| `df.mean()`                | Column-wise mean                    |
| `df.median()`              | Column-wise median                  |
| `df.std()`                 | Standard deviation                  |
| `df.min()`, `df.max()`     | Min, Max values                     |
| `df.count()`               | Count of non-null values            |
| `df.value_counts()`        | Value frequency (Series only)       |
| `df.groupby('col')`        | Group by a column                   |
| `df.pivot_table()`         | Create pivot table                  |

---

## 📁 6. Input/Output Operations

| Method                      | Description                         |
|-----------------------------|-------------------------------------|
| `pd.read_csv('file.csv')`  | Load CSV into DataFrame             |
| `df.to_csv('file.csv')`    | Save DataFrame to CSV               |
| `pd.read_excel('file.xlsx')`| Load Excel file                    |
| `df.to_excel('file.xlsx')` | Save DataFrame to Excel             |
| `pd.read_json()`           | Load JSON file                      |
| `df.to_json()`             | Save to JSON                        |
| `df.to_dict()`             | Convert to dictionary               |

---

## 🔗 7. Merging, Joining & Concatenation

| Method                     | Description                         |
|----------------------------|-------------------------------------|
| `pd.concat([df1, df2])`   | Concatenate DataFrames              |
| `pd.merge(df1, df2)`      | Merge on common columns             |
| `df.join(df2)`            | Join by index                       |
| `df.append(df2)`          | Append rows (deprecated soon)       |

---

## ⏳ 8. Time Series & Rolling Windows

| Method                          | Description                       |
|---------------------------------|-----------------------------------|
| `df.rolling(window).mean()`    | Rolling average                   |
| `df.expanding().mean()`        | Cumulative average                |
| `df.resample('M').sum()`       | Resample by month, etc.           |
| `pd.to_datetime()`             | Convert to datetime               |
| `df['date'].dt.year`           | Extract year component            |

---

✅ Use this as a reference for working with Pandas in your data analysis tasks!


# 📁 Pandas Reading & Writing Methods + Data Cleaning Methods

## 🔸 Reading and Writing Data

Pandas allows importing and exporting various file types, primarily used for tabular data processing.

| Method                        | Description                          |
|-------------------------------|--------------------------------------|
| `pd.read_csv()`               | Read CSV file                        |
| `df.to_csv()`                 | Write DataFrame to CSV               |
| `pd.read_excel()`             | Read Excel file                      |
| `df.to_excel()`               | Write to Excel file                  |
| `pd.read_json()`              | Read JSON format                     |
| `df.to_json()`                | Write to JSON format                 |
| `pd.read_html()`              | Read tables from HTML pages          |
| `df.to_dict()`                | Convert DataFrame to Python dict     |
| `df.to_sql()`                 | Write to SQL database                |

---

## 🧹 Data Cleaning Methods

Pandas provides powerful tools for handling missing data, duplicates, and data-type issues.

| Method                         | Description                                      |
|--------------------------------|--------------------------------------------------|
| `df.isnull()`                  | Check for missing values                        |
| `df.notnull()`                 | Check for non-missing values                    |
| `df.dropna()`                  | Drop rows with any missing values               |
| `df.fillna(value)`             | Fill missing values with given `value`          |
| `df.replace(old, new)`        | Replace specified values                        |
| `df.duplicated()`              | Returns Boolean Series of duplicate rows        |
| `df.drop_duplicates()`         | Remove duplicate rows                           |
| `df.astype(dtype)`             | Change column data types                        |

Use these tools to ensure data consistency and quality before analysis or modeling.


In [1]:
import pandas as pd
import numpy as np

# Sample CSV-style data using a dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Bob', None],
    'Age': [25, 30, np.nan, 30, 22],
    'City': ['NY', 'LA', 'Chicago', 'LA', 'Boston']
}

# Create DataFrame
df = pd.DataFrame(data)
print("🔹 Original DataFrame:\n", df)

# Write to CSV (simulated with buffer)
from io import StringIO
csv_data = df.to_csv(index=False)
print("\n🔹 CSV Data (written):\n", csv_data)

# Read from CSV (simulate)
df_read = pd.read_csv(StringIO(csv_data))
print("🔹 Read CSV into DataFrame:\n", df_read)

# ----------------- Data Cleaning and Manipulation Methods ------------------

print("\n🔹 Null Check:\n", df.isnull())
filled_df = df.fillna({'Name': 'Unknown', 'Age': df['Age'].mean()})
print("\n🔹 Fill Missing Values:\n", filled_df)
dropped_na = df.dropna()
print("\n🔹 Drop Rows with NA:\n", dropped_na)
replaced_df = df.replace({'City': {'NY': 'New York'}})
print("\n🔹 Replace Values in Column:\n", replaced_df)
print("\n🔹 Check Duplicates:\n", df.duplicated())
no_duplicates = df.drop_duplicates()
print("\n🔹 Drop Duplicates:\n", no_duplicates)
df['Age'] = df['Age'].fillna(0).astype(int)
print("\n🔹 Converted 'Age' to Integer:\n", df)

# ----------------- More DataFrame Operations ------------------

# Rename columns
renamed_df = df.rename(columns={'Name': 'FullName', 'City': 'Location'})
print("\n🔹 Renamed Columns:\n", renamed_df)

# Set/Reset Index
df_indexed = df.set_index('Name')
print("\n🔹 Set 'Name' as Index:\n", df_indexed)
reset_df = df_indexed.reset_index()
print("\n🔹 Reset Index:\n", reset_df)

# Sorting
sorted_by_age = df.sort_values(by='Age', ascending=False)
print("\n🔹 Sorted by Age Descending:\n", sorted_by_age)

# Filtering
over_25 = df[df['Age'] > 25]
print("\n🔹 Rows where Age > 25:\n", over_25)

# Apply custom function
df['AgePlus5'] = df['Age'].apply(lambda x: x + 5)
print("\n🔹 Apply Function (Age + 5):\n", df)

# Mapping
city_map = {'NY': 'New York', 'LA': 'Los Angeles', 'Chicago': 'Chicago', 'Boston': 'Boston'}
df['City'] = df['City'].map(city_map)
print("\n🔹 Mapped City Names:\n", df)

# Drop column
dropped_col = df.drop(columns=['AgePlus5'])
print("\n🔹 Dropped 'AgePlus5' Column:\n", dropped_col)

# Value counts
print("\n🔹 City Value Counts:\n", df['City'].value_counts())

# Group by
grouped = df.groupby('City')['Age'].mean()
print("\n🔹 Grouped by City (Mean Age):\n", grouped)

# Unique values
print("\n🔹 Unique Names:\n", df['Name'].unique())

# Describe statistics
print("\n🔹 Age Statistics:\n", df['Age'].describe())

# ----------------- Utility & Info Methods ------------------

# Data types
print("\n🔹 Data Types:\n", df.dtypes)

# Memory usage
print("\n🔹 Memory Usage (bytes):\n", df.memory_usage(deep=True))

# General info
print("\n🔹 DataFrame Info:")
df.info()

# Shape and size
print("\n🔹 Shape (Rows, Columns):", df.shape)
print("🔹 Total Elements (size):", df.size)

# Head and tail
print("\n🔹 First 3 Rows:\n", df.head(3))
print("\n🔹 Last 2 Rows:\n", df.tail(2))

# Sample rows
print("\n🔹 Random Sample (n=2):\n", df.sample(n=2))

# Column/row access
print("\n🔹 Access 'City' Column:\n", df['City'])
print("\n🔹 Access First Row (iloc):\n", df.iloc[0])
print("\n🔹 Access by Label (loc):\n", df.loc[0])

# Check if column exists
print("\n🔹 'Age' in columns:", 'Age' in df.columns)

# Column-wise null count
print("\n🔹 Null Count per Column:\n", df.isnull().sum())

# Correlation matrix
print("\n🔹 Correlation Matrix:\n", df.corr(numeric_only=True))

# Drop row by index
dropped_row = df.drop(index=0)
print("\n🔹 Dropped First Row:\n", dropped_row)

# Insert new column
df.insert(1, 'Gender', ['F', 'M', 'M', 'M', 'F'])
print("\n🔹 Inserted 'Gender' Column:\n", df)

# Rename index
df.index = ['row1', 'row2', 'row3', 'row4', 'row5']
print("\n🔹 Renamed Index:\n", df)


🔹 Original DataFrame:
       Name   Age     City
0    Alice  25.0       NY
1      Bob  30.0       LA
2  Charlie   NaN  Chicago
3      Bob  30.0       LA
4     None  22.0   Boston

🔹 CSV Data (written):
 Name,Age,City
Alice,25.0,NY
Bob,30.0,LA
Charlie,,Chicago
Bob,30.0,LA
,22.0,Boston

🔹 Read CSV into DataFrame:
       Name   Age     City
0    Alice  25.0       NY
1      Bob  30.0       LA
2  Charlie   NaN  Chicago
3      Bob  30.0       LA
4      NaN  22.0   Boston

🔹 Null Check:
     Name    Age   City
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False
4   True  False  False

🔹 Fill Missing Values:
       Name    Age     City
0    Alice  25.00       NY
1      Bob  30.00       LA
2  Charlie  26.75  Chicago
3      Bob  30.00       LA
4  Unknown  22.00   Boston

🔹 Drop Rows with NA:
     Name   Age City
0  Alice  25.0   NY
1    Bob  30.0   LA
3    Bob  30.0   LA

🔹 Replace Values in Column:
       Name   Age      City
0    Alice  25.0  New York
1 

# 📘 Matplotlib Methods – Full Explanation and Categorization

---

## 🎨 1. Plotting Methods

| **Method**                         | **Description** |
|-----------------------------------|-----------------|
| `plot(x, y)`                      | Line plot of y versus x. |
| `bar(x, height)`                  | Vertical bar chart. |
| `barh(y, width)`                  | Horizontal bar chart. |
| `scatter(x, y)`                   | Scatter plot of (x, y) points. |
| `hist(data, bins)`                | Histogram showing the distribution of data. |
| `boxplot(data)`                   | Box-and-whisker plot for statistical summary. |
| `pie(sizes)`                      | Pie chart of proportions. |
| `stackplot(x, y_stack)`           | Stacked area plot showing multiple values stacked over x. |

---

## 🧰 2. Plot Customization

| **Method**                         | **Description** |
|-----------------------------------|-----------------|
| `title("Title")`                  | Sets the title of the plot. |
| `xlabel("X Axis")`                | Labels the x-axis. |
| `ylabel("Y Axis")`                | Labels the y-axis. |
| `legend()`                        | Adds a legend for labeled plots. |
| `grid(True)`                      | Adds a grid background. |
| `annotate()`                      | Adds annotation with optional arrow. |
| `text(x, y, "label")`             | Places custom text at (x, y). |

---

## 📏 3. Axes and Ticks

| **Method**                         | **Description** |
|-----------------------------------|-----------------|
| `xlim([min, max])` / `ylim()`     | Set limits for x or y axis. |
| `xticks()` / `yticks()`           | Set custom tick positions and labels. |
| `tick_params()`                   | Customize tick properties (e.g., rotation). |
| `spines['top'].set_visible(False)`| Hide or show specific plot borders (spines). |

---

## 🧬 4. Layouts & Subplots

| **Method**                         | **Description** |
|-----------------------------------|-----------------|
| `figure(figsize=(w, h))`          | Creates a new figure with a specific size. |
| `subplot(nrows, ncols, index)`    | Places multiple plots in a grid layout. |
| `subplots()`                      | Returns a tuple (figure, axes) for object-oriented plotting. |
| `constrained_layout=True`         | Automatically adjusts subplots to fit without overlap. |

---

## 🧪 5. Advanced Axes Features

| **Method**                         | **Description** |
|-----------------------------------|-----------------|
| `twinx()`                         | Creates a second Y-axis sharing the same X-axis. |
| `set_xticklabels()`               | Customizes tick labels on x-axis. |
| `set_xticks()`                    | Sets specific tick locations on the x-axis. |

---

## 💾 6. Display and Save

| **Method**                         | **Description** |
|-----------------------------------|-----------------|
| `show()`                          | Renders the current figure to screen. |
| `savefig("filename.png")`         | Saves the current figure to an image file. |

---

## ⚙️ 7. Object-Oriented API (OOP)

| **Method**                         | **Description** |
|-----------------------------------|-----------------|
| `fig, ax = subplots()`            | Creates figure and axis objects. |
| `ax.plot()`                       | Plots directly using the axis object. |
| `ax.set_title()` / `.set_xlabel()`| Set titles and labels using OOP style. |
| `ax.legend()`                     | Adds legend to axis object. |
| `ax.grid()`                       | Adds grid to the axis object. |

---

## 🧾 8. Utility and Data Inspection

| **Method**                         | **Description** |
|-----------------------------------|-----------------|
| `x.shape`                         | Returns the shape (size/dimensions) of array `x`. |
| `y[:5]`                           | Displays the first 5 elements of array `y`. |

In [4]:
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Segoe UI Emoji'
import numpy as np

# Sample data
x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)
categories = ['A', 'B', 'C', 'D']
values = [23, 45, 56, 78]
random_data = np.random.normal(0, 1, 1000)

# Create main figure
fig, axs = plt.subplots(4, 3, figsize=(18, 16), constrained_layout=True)
fig.suptitle("🔧 All-in-One Matplotlib Plotting Showcase", fontsize=18)

# 1. Line Plot with Custom Style & Annotation
axs[0, 0].plot(x, y1, label='sin(x)', color='blue', linestyle='--', linewidth=2, marker='o')
axs[0, 0].set_title('Line Plot with Marker & Annotation')
axs[0, 0].set_xlabel('X Axis')
axs[0, 0].set_ylabel('Y Axis')
axs[0, 0].grid(True)
axs[0, 0].legend()
axs[0, 0].annotate('Peak', xy=(1.5, 1), xytext=(2, 1.5),
                   arrowprops=dict(facecolor='black', shrink=0.05))

# 2. Bar Plot with Custom Colors & Axis Limits
axs[0, 1].bar(categories, values, color=['red', 'green', 'blue', 'orange'])
axs[0, 1].set_title('Bar Plot with Axis Limits')
axs[0, 1].set_ylim(0, 100)

# 3. Horizontal Bar with Text & Rotated Ticks
axs[0, 2].barh(categories, values, color='lightgreen')
axs[0, 2].set_title('Horizontal Bar')
axs[0, 2].set_xticks([0, 25, 50, 75, 100])
axs[0, 2].set_xlabel('Score')
axs[0, 2].text(10, 'B', '← Label B', color='red')

# 4. Scatter Plot with Custom Markers
axs[1, 0].scatter(x, y2, color='purple', label='cos(x)', marker='*')
axs[1, 0].set_title('Scatter with Custom Marker')
axs[1, 0].legend()

# 5. Histogram with Density
axs[1, 1].hist(random_data, bins=20, color='pink', density=True, edgecolor='black')
axs[1, 1].set_title('Histogram with Density')

# 6. Box Plot with Notch
axs[1, 2].boxplot([random_data, np.random.normal(1, 2, 1000)], notch=True, patch_artist=True,
                  boxprops=dict(facecolor='lightblue'))
axs[1, 2].set_title('Box Plot (Notched)')
axs[1, 2].set_xticklabels(['Dist1', 'Dist2'])

# 7. Pie Chart with Shadow
axs[2, 0].pie(values, labels=categories, autopct='%1.1f%%', shadow=True, startangle=140)
axs[2, 0].set_title('Pie Chart with Shadow')

# 8. Stack Plot
axs[2, 1].stackplot(x, np.row_stack([np.sin(x), np.sin(x + 1), np.sin(x + 2)]),
                    labels=['A', 'B', 'C'], alpha=0.6)
axs[2, 1].set_title('Stack Plot')
axs[2, 1].legend(loc='upper left')

# 9. Shared Axis Plot
x2 = np.arange(0, 4)
y2a = [1, 4, 9, 16]
y2b = [2, 3, 5, 7]
axs[2, 2].plot(x2, y2a, label='Line A')
axs[2, 2].plot(x2, y2b, label='Line B')
axs[2, 2].set_title('Shared Axes Plot')
axs[2, 2].legend()

# 10. Twin Y-Axis
ax_main = axs[3, 0]
ax_twin = ax_main.twinx()
ax_main.plot(x, y1, 'g-', label='sin(x)')
ax_twin.plot(x, y2, 'b-', label='cos(x)')
ax_main.set_title('Twin Y Axes')
ax_main.set_ylabel('sin(x)', color='g')
ax_twin.set_ylabel('cos(x)', color='b')

# 11. Customize Spines & Ticks
axs[3, 1].plot(x, y1, color='black')
axs[3, 1].set_title('Custom Spines')
axs[3, 1].spines['top'].set_visible(False)
axs[3, 1].spines['right'].set_visible(False)
axs[3, 1].tick_params(axis='x', rotation=45)

# 12. Object-Oriented API with Manual Layout
fig2, ax = plt.subplots(figsize=(5, 4))
ax.plot(x, y2, label='cos(x)', color='brown')
ax.set_title('OOP API Plot')
ax.set_xlabel('X Axis')
ax.set_ylabel('Cosine')
ax.legend()
ax.grid(True)

# Save final output
fig.savefig("full_matplotlib_methods.png")
fig2.savefig("oop_api_plot.png")

plt.show()

# Display data utility
print("🎯 x.shape =", x.shape)
print("🧪 First 5 y1 =", y1[:5])


🎯 x.shape = (100,)
🧪 First 5 y1 = [0.         0.10083842 0.20064886 0.2984138  0.39313661]


In [18]:
from pandas import *
import matplotlib.pyplot as plt

# Task 1: Load the dataset into a Pandas Data Frame and examint the first few rows.
shooting_dataset = read_csv("shooting-1982-2023.csv")
shooting_dataframe = DataFrame(shooting_dataset)
print(shooting_dataframe.head(10))


                                   case                    location      date  \
0   Nashville religious school shooting               Nashville, TN   3-27-23   
1    Michigan State University shooting      East Lansing, Michigan   2-13-23   
2          Half Moon Bay spree shooting   Half Moon Bay, California   1-23-23   
3         LA dance studio mass shooting   Monterey Park, California   1-21-23   
4             Virginia Walmart shooting        Chesapeake, Virginia  11-22-22   
5                   LGBTQ club shooting  Colorado Springs, Colorado  11-19-22   
6       University of Virginia shooting   Charlottesville, Virginia  11-13-22   
7                Raleigh spree shooting   Hedingham, North Carolina  10-13-22   
8          Greenwood Park Mall shooting          Greenwood, Indiana   7-17-22   
9  Highland Park July 4 parade shooting     Highland Park, Illinois    7-4-22   

                                             summary  fatalities injured  \
0  Audrey Hale, 28, who was a fo

In [16]:
# Task 2: Checck the dimensions of the dataset (number of rows and columns).
print("Shape:", shooting_dataframe.shape)

Shape: (140, 21)


In [17]:
# Task 3: Identify and handle missing values in the dataset.
print("\n Missing values:\n", shooting_dataframe.isnull().sum())
shooting_dataframe = shooting_dataframe.dropna()
print("\nMissing values:\n", shooting_dataframe.isnull().sum())



 Missing values:
 case                                0
location                            0
date                                0
summary                             0
fatalities                          0
injured                             0
total_victims                       0
location.1                          0
age_of_shooter                      0
prior_signs_mental_health_issues    0
mental_health_details               0
weapons_obtained_legally            0
where_obtained                      0
weapon_type                         0
weapon_details                      0
race                                0
gender                              0
latitude                            0
longitude                           0
type                                0
year                                0
dtype: int64

Missing values:
 case                                0
location                            0
date                                0
summary                             0


In [24]:
# Task 4: Analyze the distribution of gun violence incidents over the years using a line plot.
incidents_over_years = shooting_dataframe.groupby('year').sum()

plt.figure(figsize = (14, 10), dpi = 80, facecolor = "#264653")
plt.title("US Gun Violence fatalities between 1982-2023")
plt.plot(incidents_over_years.index, incidents_over_years["fatalities"], 'o-')
plt.xlabel("Year")
plt.ylabel("Fatalities")
plt.xticks(incidents_over_years.index, rotation = 90)
plt.show()

In [32]:
# Task 5: Calculate the total number of fatatlities and injuries caused by mass shootings.
total_fatalities = shooting_dataframe.groupby('type').sum()['fatalities'].loc['Mass']
print(f" Total fatalities between 1982-2023 caused by mass shooting is {total_fatalities}")

shooting_dataframe['injured'] = to_numeric(arg = shooting_dataframe["injured"], errors = "coerce")
shooting_dataframe.fillna({'injured': 5}, inplace=True)
shooting_dataframe["injured"] = shooting_dataframe["injured"].astype(int)
total_injured = shooting_dataframe[['type', 'injured']].groupby('type').sum()["injured"].loc["Mass"]
print(f"Total injured between 1982-2023 caused by mass shooting is {total_injured}")

 Total fatalities between 1982-2023 caused by mass shooting is 975
Total injured between 1982-2023 caused by mass shooting is 1418


In [47]:
# Task 6: Visualize the top 10 states with the highest number of incidents using a bat chart
state = shooting_dataframe['location'].str.split(",").str[-1].str.strip()
# shooting_dataframe.insert(2, "State", state)
incidents_per_state = shooting_dataframe["State"].value_counts().head(10)
plt.bar(incidents_per_state.index, incidents_per_state)
plt.title("Top 10 states with the highest number of Gun Violence incident within 1982-2023")
plt.xticks(fontsize = 10, rotation = 45)
plt.show()

In [48]:
# Task 7: Determine the most common locations where mass shooting occur.
location_with_highest_incident = shooting_dataframe['location'].value_counts()
print(f"location with highest incident is {location_with_highest_incident}")

location with highest incident is location
Colorado Springs, Colorado    3
San Francisco, California     2
Dallas, Texas                 2
Orange, California            2
Orlando, Florida              2
                             ..
Cincinnati, Ohio              1
Bakersfield, California       1
Perryman, Maryland            1
Pittsburgh, Pennsylvania      1
Miami, Florida                1
Name: count, Length: 130, dtype: int64


In [49]:
# Task 8: Calculate the average number of fatalities and injuries per incident.
avg_fatalities = shooting_dataframe['fatalities'].mean()
avg_injuries = shooting_dataframe['injured'].mean()

print(f"The average fatalities due to gun violence per incident (1982–2023) is: {avg_fatalities:.2f}")
print(f"The average injuries due to gun violence per incident (1982–2023) is: {avg_injuries:.2f}")


The average fatalities due to gun violence per incident (1982–2023) is: 7.81
The average injuries due to gun violence per incident (1982–2023) is: 11.24


In [56]:

# Task 9: Explore relationship between fatalities and injuries

plt.figure(figsize=(10, 6))

# Create scatter plot
plt.scatter(
    shooting_dataframe['fatalities'],
    shooting_dataframe['injured'],
    s=100,               # 🔍 Point size increased
    c='red',             # Color of points
    alpha=0.6,           # Transparency
    edgecolors='black'   # Border for better visibility
)

# Plot decorations
plt.title("Relationship Between Fatalities and Injuries (1982–2023)")
plt.xlabel("Number of Fatalities")
plt.ylabel("Number of Injuries")
plt.grid(True)
plt.tight_layout()
plt.show()


In [60]:
# Task 10: Analyze the trend of incidents based on the shooter's gender using a pie chart.
shooting_based_on_gender = shooting_dataframe.groupby('gender').sum()['fatalities']
labels = ["F", "F (Identified as transgender)", "Female", "M", "Male", "Male & Female"]
plt.pie(shooting_based_on_gender)
plt.axis("equal")
plt.legend(labels, loc = "upper left")
plt.savefig("Gun Violence in USA Trend based on shooter's gender.png")
plt.show()